'use strict';
const $=s=>document.querySelector(s);
const tokenFromLink=new URLSearchParams(location.hash.slice(1)).get('token');
if(tokenFromLink){sessionStorage.setItem('coach-token',tokenFromLink);history.replaceState(null,'',location.pathname);}
let token=sessionStorage.getItem('coach-token')||'', state={revision:0,profile:null};
const workoutNames={"RUN_EASY": "Rolig løp", "RUN_THRESHOLD": "Terskel løp", "BIKE_AEROBIC": "Rolig sykkel", "BIKE_SWEETSPOT": "Sweetspot sykkel", "BIKE_THRESHOLD": "Terskel sykkel", "SWIM_TECHNIQUE": "Svømmeteknikk", "SWIM_CSS": "CSS-svømming", "STRENGTH_GENERAL": "Styrke", "CROSSFIT": "CrossFit", "RUN_LONG": "Langtur løp", "RUN_INTERVAL": "Løpsintervaller", "RUN_HILLS": "Bakkeløp", "RUN_BRICK": "Kombinasjonsløp", "BIKE_ENDURANCE": "Langtur sykkel", "BIKE_VO2": "Sykkelintervaller", "BIKE_BRICK": "Kombinasjonssykkel", "SWIM_ENDURANCE": "Utholdenhetssvømming", "SWIM_OPEN_WATER": "Åpent vann", "STRENGTH_FULLBODY": "Helkroppsstyrke", "STRENGTH_LOWER": "Underkroppsstyrke", "STRENGTH_UPPER": "Overkroppsstyrke", "MOBILITY": "Mobilitet", "RECOVERY": "Restitusjon"};
const reasonNames={INCOMPLETE_RECENT_CHECKIN:'Ingen progresjon: nylig innsjekk mangler responsdata.',NO_RECENT_CHECKIN:'Ingen progresjon: registrer en fersk innsjekk.',PAIN_REPORTED:'Smerte er registrert.',RECOVERY_REVIEW:'Restitusjonen trenger vurdering.',CARRY_FORWARD_APPROVED_STRUCTURE_NO_AUTOMATIC_PROGRESSION:'Viderefører godkjent ukestruktur uten automatisk progresjon.',STARTER_DRAFT_REQUIRES_HQ_REVIEW:'Et forsiktig startutkast til HQ.',NO_CURRENT_COMPARABLE_EVIDENCE_KEEP_DOSE:'Beholder dosen: mangler aktuell, sammenlignbar evidens.',KEEP_EXISTING_PLAN:'Beholder eksisterende plan.',PAIN_REQUIRES_HQ_REVIEW_NO_AUTOMATIC_DOSE:'Smerte må vurderes av HQ før videre belastning.',PAIN_REQUIRES_HQ_REVIEW:'Godkjenning blokkert: avklar rapportert smerte.',SPACING_SIGNAL_REQUIRES_HQ_REVIEW:'HQ bør vurdere avstand mellom øktene.',NON_EASY_RECOVERY_CHANGE_REQUIRES_HQ:'HQ må vurdere endringer av kvalitetsøkter.'};
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;}
function notice(text,error=false){const n=$('#notice');n.textContent=text;n.hidden=false;n.className=error?'error':'';}
async function api(path,body,hq){const headers={'Authorization':'Bearer '+token};if(body)headers['Content-Type']='application/json';if(hq)headers['X-HQ-Token']=$('#hq-token').value;const r=await fetch(path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok){const error=Error(data.error||'Forespørselen feilet');error.status=r.status;throw error;}return data;}
async function action(fn){try{await fn();await refresh();}catch(e){if(e.status===409)await refresh();notice(e.message,true);}}
function values(form){return Object.fromEntries(new FormData(form));}
function numberOrNull(v){return v===''?null:Number(v);}
function isoToday(){return new Date().toLocaleDateString('sv-SE');}
function monday(){const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toLocaleDateString('sv-SE');}
function id(prefix){return prefix+'-'+crypto.randomUUID().slice(0,12);}
function checked(selector){return [...document.querySelectorAll(selector+' input:checked')].map(n=>n.value);}
function sessionRow(s){const row=node('div',undefined,'session');const d=new Date(s.date+'T12:00:00');const day=node('div',d.toLocaleDateString('nb-NO',{weekday:'short'}),'session-day');day.append(node('b',d.getDate()));const info=node('div');info.append(node('strong',workoutNames[s.workout_type]||s.workout_type),node('p',s.purpose+(s.locked?' · Låst':'')));row.append(day,info,node('div',s.duration_min+' min','session-time'));return row;}
async function refresh(){state=await api('/api/state');$('#connect').hidden=true;$('#connection').textContent='● Lokal coach';if(state.needs_onboarding){$('#settings').scrollIntoView();return;}$('#greeting').textContent='Hei, '+state.profile.name+'.';$('#date-line').textContent=new Date(state.today+'T12:00:00').toLocaleDateString('nb-NO',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#coach-message').textContent=state.coach_message;$('#focus-title').textContent=state.alerts.includes('PAIN_REPORTED')?'Lytt til responsen. Juster med omtanke.':state.upcoming.length?'En tydelig plan. Ett steg av gangen.':'La oss forme en gjennomførbar uke.';$('#completed').textContent=state.weekly_review.completed;$('#minutes').textContent=state.weekly_review.actual_minutes;$('#goal-count').textContent=state.goals.filter(g=>g.status==='ACTIVE').length;$('#data-status').textContent={MISSING:'Mangler',INCOMPLETE:'Ufullstendig',RECORDED:'Registrert'}[state.health.data_quality];$('#data-detail').textContent='Treningseffekt er ikke validert';renderPlan();renderGoals();renderProposals();fillProfile();renderSourceContext();await renderGarmin();}
function renderPlan(){const box=$('#plan-list');box.replaceChildren();const sessions=state.plan?.sessions||[];if(!sessions.length)box.append(node('p','Ingen godkjent plan ennå. Lag et forslag nedenfor.'));sessions.slice().sort((a,b)=>a.date.localeCompare(b.date)).forEach(s=>box.append(sessionRow(s)));const select=$('#session-select');const old=select.value;select.replaceChildren(node('option','Velg økt'));select.firstChild.value='';sessions.filter(s=>s.date<=state.today).forEach(s=>{const o=node('option',s.date+' · '+workoutNames[s.workout_type]);o.value=s.id;select.append(o);});if([...select.options].some(o=>o.value===old))select.value=old;$('#week-start').value=state.plan?.week_start||monday();}
function renderGoals(){const box=$('#goal-list');box.replaceChildren();if(!state.goals.length)box.append(node('p','Sett et målbart mål nedenfor.'));state.goals.forEach(g=>{const card=node('article',undefined,'goal');card.append(node('h3',g.title),node('p','Mål: '+g.target+' '+g.unit+' innen '+g.target_date));const v=node('div',undefined,'goal-values');v.append(node('span','Sist: '+g.current+' '+g.unit),node('span',g.progress_percent+' % av endringen'));const progress=node('progress');progress.max=100;progress.value=g.progress_percent;progress.setAttribute('aria-label','Målprogresjon');card.append(v,progress);const milestones=node('div',undefined,'milestones');g.milestones.forEach(m=>milestones.append(node('span',m.date+': '+m.reference_value+' '+g.unit)));card.append(milestones,node('p',g.milestone_note,'hint'));const form=node('form');const label=node('label','Ny måling');const input=node('input');input.type='number';input.step='any';input.required=true;input.setAttribute('aria-label','Ny måling for '+g.title);label.append(input);const button=node('button','Registrer');form.append(label,button);form.onsubmit=e=>{e.preventDefault();action(async()=>{const original={};for(const key of ['id','athlete_id','title','metric','unit','baseline','target','direction','start_date','target_date','measurements','status'])original[key]=g[key];original.measurements=original.measurements.filter(m=>m.date!==state.today).concat([{date:state.today,value:Number(input.value),source:'USER_CHECKIN'}]);await api('/api/goal',{value:original,expected_revision:state.revision});notice('Målingen er lagret.');});};card.append(form);box.append(card);});}
function renderProposals(){const box=$('#proposal-list');box.replaceChildren();const proposals=state.proposals.slice().reverse().slice(0,5);if(!proposals.length)box.append(node('p','Ingen forslag ennå.'));proposals.forEach(p=>{const card=node('article',undefined,'proposal');card.append(node('h3','Uke fra '+p.candidate.week_start+' · '+({PENDING_HQ:'Til vurdering',APPROVED:'Godkjent',REJECTED:'Avvist'}[p.status]||p.status)));p.reason_codes.forEach(r=>card.append(node('p',reasonNames[r]||r)));p.blockers.forEach(r=>card.append(node('p',reasonNames[r]||r,'warning')));if(p.changes.length){p.changes.forEach(c=>card.append(node('p',workoutNames[c.after.workout_type]+': '+c.before.duration_min+' → '+c.after.duration_min+' min ('+c.state+')')));}else{card.append(node('p','Ingen doseendring. '+p.candidate.sessions.length+' økter i forslaget.'));}const details=node('details');details.append(node('summary','Se hele forslaget'));p.candidate.sessions.forEach(s=>details.append(sessionRow(s)));card.append(details);if(p.status==='PENDING_HQ'){const actions=node('div',undefined,'proposal-actions');for(const [decision,label] of [['APPROVED','Godkjenn som HQ'],['REJECTED','Avvis']]){const b=node('button',label,decision==='REJECTED'?'secondary':'');b.disabled=decision==='APPROVED'&&(p.blockers.length>0||p.base_revision+1!==state.revision);b.onclick=()=>action(async()=>{await api('/api/hq/decision',{proposal_id:p.id,decision,expected_revision:state.revision},true);notice(decision==='APPROVED'?'HQ har godkjent den lokale planen.':'Forslaget er avvist.');});actions.append(b);}card.append(actions);if(p.base_revision+1!==state.revision)card.append(node('p','Datagrunnlaget er endret. Lag et nytt forslag før godkjenning.','hint'));}box.append(card);});}
function fillProfile(){const f=$('#profile-form'),p=state.profile;for(const k of ['name','timezone','weekly_minutes','max_session_minutes','coaching_tone','limitations'])f.elements[k].value=p[k];f.elements.equipment.value=p.equipment.join(', ');for(const [container,selected] of [['#days',p.available_days.map(String)],['#workouts',p.preferred_workouts],['#blocked-workouts',p.blocked_workouts]])document.querySelectorAll(container+' input').forEach(i=>i.checked=selected.includes(i.value));}
$('#connect-form').onsubmit=e=>{e.preventDefault();token=values(e.target).token;sessionStorage.setItem('coach-token',token);action(async()=>{});};
$('#profile-form').onsubmit=e=>{e.preventDefault();const v=values(e.target);action(async()=>{await api('/api/profile',{expected_revision:state.revision,value:{athlete_id:state.profile?.athlete_id||id('athlete'),name:v.name,timezone:v.timezone,weekly_minutes:numberOrNull(v.weekly_minutes),max_session_minutes:numberOrNull(v.max_session_minutes),available_days:checked('#days').map(Number),preferred_workouts:checked('#workouts'),blocked_workouts:checked('#blocked-workouts'),equipment:v.equipment.split(',').map(x=>x.trim()).filter(Boolean),limitations:v.limitations,coaching_tone:v.coaching_tone}});notice('Profilen er lagret.');});};
$('#goal-form').elements.start_date.value=isoToday();$('#week-start').value=monday();
$('#goal-form').onsubmit=e=>{e.preventDefault();const v=values(e.target);action(async()=>{if(!state.profile)throw Error('Lagre profilen først.');await api('/api/goal',{expected_revision:state.revision,value:{id:id('goal'),athlete_id:state.profile.athlete_id,title:v.title,metric:v.metric,unit:v.unit,baseline:Number(v.baseline),target:Number(v.target),direction:Number(v.target)>Number(v.baseline)?'INCREASE':'DECREASE',start_date:v.start_date,target_date:v.target_date,measurements:[],status:'ACTIVE'}});notice('Målet er lagret.');});};
$('#checkin-form').onsubmit=e=>{e.preventDefault();const v=values(e.target);action(async()=>{if(!state.profile)throw Error('Lagre profilen først.');await api('/api/checkin',{expected_revision:state.revision,value:{id:id('checkin'),athlete_id:state.profile.athlete_id,session_id:v.session_id,observed_at:new Date().toISOString(),status:v.status,duration_min:Number(v.duration_min),rpe:numberOrNull(v.rpe),quality:v.quality===''?null:Number(v.quality)/100,pain:numberOrNull(v.pain),energy:numberOrNull(v.energy),recovery:v.recovery,notes:v.notes}});notice('Innsjekken er lagret.');});};
$('#propose').onclick=()=>action(async()=>{await api('/api/propose',{expected_revision:state.revision,week_start:$('#week-start').value});notice('Forslaget er klart til HQ-vurdering.');});
function bubble(text,user=false,mode){const n=node('p',text,'bubble'+(user?' user':''));if(mode)n.append(node('small',mode));$('#chat-log').append(n);$('#chat-log').scrollTop=$('#chat-log').scrollHeight;}
async function chat(message){bubble(message,true);try{const r=await api('/api/chat',{message,cloud_consent:$('#cloud-consent').checked});const modes={DETERMINISTIC_COACH:'Lokalt faktasvar',LLM_LANGUAGE_ONLY:'AI-formulert · ingen planendring',FALLBACK_NOT_CONFIGURED:'Lokalt svar · AI er ikke konfigurert',FALLBACK_PROVIDER_UNAVAILABLE:'Lokalt svar · AI svarte ikke'};bubble(r.message,false,modes[r.mode]);}catch(e){notice(e.message,true);}}
$('#chat-form').onsubmit=e=>{e.preventDefault();const message=$('#message').value;$('#message').value='';chat(message);};document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>chat(b.dataset.question));
for(const [selector,url,hq] of [['#source-file','/api/source-import',false],['#evidence-file','/api/import',false],['#plan-file','/api/hq/import',true]])$(selector).onchange=e=>action(async()=>{const file=e.target.files[0];if(!file)return;await api(url,{value:JSON.parse(await file.text()),expected_revision:state.revision},hq);notice('Dataene er importert.');e.target.value='';});
$('#health').onclick=()=>action(async()=>{const h=await api('/api/health');$('#health-output').hidden=false;$('#health-output').textContent=JSON.stringify(h,null,2);});$('#backup').onclick=()=>action(async()=>{const b=await api('/api/backup',{expected_revision:state.revision});notice('Sikkerhetskopi opprettet: '+b.file);});$('#export').onclick=()=>action(async()=>{const d=await api('/api/export');const a=node('a');const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.href=url;a.download='ai-coach-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
['Man','Tir','Ons','Tor','Fre','Lør','Søn'].forEach((name,i)=>{const l=node('label',name);const input=node('input');input.type='checkbox';input.value=i;input.checked=[0,2,4].includes(i);l.prepend(input);$('#days').append(l);});for(const box of ['#workouts','#blocked-workouts'])Object.entries(workoutNames).forEach(([key,name])=>{const l=node('label',name),input=node('input');input.type='checkbox';input.value=key;input.checked=box==='#workouts'&&key==='RUN_EASY';l.prepend(input);$(box).append(l);});
refresh().catch(e=>{$('#connect').hidden=false;$('#connection').textContent='Ikke tilkoblet';notice(e.message,true);});

function renderSourceContext(){
 const source=state.source_context, box=$('#source-overview');$('#source-context').hidden=!source;if(!source)return;box.replaceChildren();
 box.append(node('p',''+source.activity_provider+' importert '+source.collected_at+' · '+source.total_activities+' aktiviteter · '+source.linked_plans+' eksplisitte plan–aktivitet-koblinger.'));
 box.append(node('p',source.stale?'Aktivitetsdata er eldre enn ett døgn; hent ferske data før nye vurderinger.':'Datert import. Automatisk løpende synk er ikke aktiv.'));
 box.append(node('p',source.assessment));
 box.append(node('h3','Tilgjengelighet'),node('p',source.availability.description||'Ikke avklart'));
 box.append(node('h3','Treningsmengde fra registrerte økter'));
 const table=node('table'),head=node('tr');['Periode','Aktiviteter','Aktiv tid (timer)','Forløpt tid (timer)'].forEach(x=>head.append(node('th',x)));table.append(head);
 source.periods.forEach(p=>{const row=node('tr');[p.period,p.count,(p.active_sec/3600).toFixed(1),(p.elapsed_sec/3600).toFixed(1)].forEach(x=>row.append(node('td',x)));table.append(row);});box.append(table);source.periods.filter(p=>!p.period.startsWith('Uke ')).forEach(p=>box.append(node('p',p.period+' · '+Object.entries(p.subsports).map(([sport,seconds])=>sport+': '+(seconds/3600).toFixed(1)+' t').join(' · '))));box.append(node('p','Aktiv tid og forløpt tid er ulike kildemål. Randuker er delvise. Hiking, klatring og transport teller i totalen; dette er ikke et ukentlig mål.','hint'));
 box.append(node('h3','Gjeldende progresjonsramme'));source.progression.forEach(p=>box.append(node('p',p.description)));
 source.plan_conflicts.forEach(p=>box.append(node('p',p.local_date+' · '+p.title+' · '+p.dose_note,'warning')));
 source.open_questions.forEach(q=>box.append(node('p',q,'hint')));
 $('#goal-count').textContent=source.goals.length+state.goals.filter(g=>g.status==='ACTIVE').length;
 const goals=$('#goal-list');source.goals.forEach(g=>{const card=node('article',undefined,'goal');card.append(node('h3',g.title),node('p',g.description),node('p','Kilde: bekreftet prosjektkontekst.','hint'));goals.prepend(card);});
 if(!state.plan){const plans=$('#plan-list');plans.replaceChildren(node('p','Importert HQ-plan · visning uten lokale planendringer.'));
 if(source.plan_stale)plans.append(node('p','HQ-planen er ikke nylig oppdatert. Garmin-synk bekrefter ikke dagens plan.','warning'));
 if(source.today_rest)plans.append(node('p','I dag: planlagt hvile, eksplisitt fra HQ.'));
 source.upcoming.forEach(p=>{const card=node('article',undefined,'goal');card.append(node('h3',p.local_date+' · '+p.title),node('p',p.dose_note));plans.append(card);});
 plans.append(node('p','Plan hentet: '+source.plan_collected_at+' · Planimportens sluttdato: '+source.plan_end+'. Tomme dager uten eksplisitt HQ-hvile er ikke automatisk hviledager.','hint'));
 $('#propose').disabled=true;$('#propose').title='Ekstern HQ beholder planautoriteten. Dette er en lesekopi.';}
 const select=$('#session-select');if(!state.plan){select.replaceChildren(node('option','Velg økt'));select.firstChild.value='';
 const rows=source.plans.filter(p=>p.local_date<=state.today).map(p=>({id:p.id,date:p.local_date,title:p.title}));
 source.activities.forEach(a=>rows.push({id:'actual-'+a.id,date:a.local_date,title:'Registrert aktivitet · '+a.title}));
 rows.sort((a,b)=>b.date.localeCompare(a.date)).forEach(r=>{const o=node('option',r.date+' · '+r.title);o.value=r.id;select.append(o);});}
 $('#coach-message').textContent=source.assessment;
 $('#activity-label').textContent='Registrerte aktiviteter';$('#completed').textContent=source.recent_count;$('#minutes').textContent=source.recent_minutes;
 $('#data-status').textContent=source.stale?'Utdatert':'Importert';$('#data-detail').textContent='Respons og treningseffekt er ikke bekreftet';
}

async function renderGarmin(){const g=await api("/api/garmin/status");$("#garmin-status").textContent=(g.connected?"Tilkoblet":"Lokal innlogging kreves")+" · Siste synk: "+(g.last_success||"aldri")+" · "+g.activities+" aktiviteter"+(g.last_error?" · "+g.last_error:"");}
$("#garmin-sync").onclick=async()=>{const b=$("#garmin-sync"),st=$("#garmin-status");b.disabled=true;st.className="";st.textContent="Synkroniserer…";let msg,err=false,r;try{r=await api("/api/garmin/sync",{expected_revision:state.revision});}catch(e){msg=e.message||"Synk feilet";err=true;if(e.status===409){try{await refresh();}catch(_){}}}
if(!err){try{await refresh();}catch(_){}let g=null;try{g=await api("/api/garmin/status");}catch(_){}msg="Synkronisert: "+r.activities+" aktiviteter · Siste synk: "+((g&&g.last_success)||"ukjent");}
st.textContent=msg;st.className=err?"error":"";b.disabled=false;};
