"""Workout identity and physiological stimulus are distinct dimensions."""

TAXONOMY_VERSION = "1.0"
WORKOUTS = {
    "RUN_EASY": ("RUN", ["AEROBIC"]),
    "RUN_THRESHOLD": ("RUN", ["THRESHOLD"]),
    "BIKE_AEROBIC": ("BIKE", ["AEROBIC"]),
    "BIKE_SWEETSPOT": ("BIKE", ["SWEETSPOT"]),
    "BIKE_THRESHOLD": ("BIKE", ["THRESHOLD"]),
    "SWIM_TECHNIQUE": ("SWIM", ["TECHNIQUE", "AEROBIC"]),
    "SWIM_CSS": ("SWIM", ["THRESHOLD"]),
    "STRENGTH_GENERAL": ("STRENGTH", ["STRENGTH"]),
    "CROSSFIT": ("MIXED", ["STRENGTH", "ANAEROBIC"]),
}
STIMULI = ["AEROBIC", "THRESHOLD", "SWEETSPOT", "TECHNIQUE", "STRENGTH", "ANAEROBIC"]
STATES = ["KEEP", "PROGRESS", "CONSOLIDATE", "REDUCE", "MOVE", "AVOID_COMBINATION", "INSUFFICIENT_EVIDENCE"]
