"""Workout identity and physiological stimulus are distinct dimensions."""

TAXONOMY_VERSION = "1.1"
WORKOUTS = {
    "RUN_EASY": ("RUN", ["AEROBIC"]),
    "RUN_LONG": ("RUN", ["AEROBIC", "LONG_ENDURANCE"]),
    "RUN_THRESHOLD": ("RUN", ["THRESHOLD"]),
    "RUN_INTERVAL": ("RUN", ["VO2MAX"]),
    "RUN_HILLS": ("RUN", ["STRENGTH_ENDURANCE"]),
    "RUN_BRICK": ("RUN", ["AEROBIC", "BRICK"]),
    "BIKE_AEROBIC": ("BIKE", ["AEROBIC"]),
    "BIKE_ENDURANCE": ("BIKE", ["AEROBIC", "LONG_ENDURANCE"]),
    "BIKE_SWEETSPOT": ("BIKE", ["SWEETSPOT"]),
    "BIKE_THRESHOLD": ("BIKE", ["THRESHOLD"]),
    "BIKE_VO2": ("BIKE", ["VO2MAX"]),
    "BIKE_BRICK": ("BIKE", ["AEROBIC", "BRICK"]),
    "SWIM_TECHNIQUE": ("SWIM", ["TECHNIQUE", "AEROBIC"]),
    "SWIM_ENDURANCE": ("SWIM", ["AEROBIC"]),
    "SWIM_CSS": ("SWIM", ["THRESHOLD"]),
    "SWIM_OPEN_WATER": ("SWIM", ["AEROBIC", "SKILL"]),
    "STRENGTH_GENERAL": ("STRENGTH", ["STRENGTH"]),
    "STRENGTH_FULLBODY": ("STRENGTH", ["STRENGTH"]),
    "STRENGTH_LOWER": ("STRENGTH", ["STRENGTH"]),
    "STRENGTH_UPPER": ("STRENGTH", ["STRENGTH"]),
    "MOBILITY": ("MIXED", ["MOBILITY"]),
    "RECOVERY": ("MIXED", ["RECOVERY"]),
    "CROSSFIT": ("MIXED", ["STRENGTH", "ANAEROBIC"]),
}
STIMULI = [
    "AEROBIC", "THRESHOLD", "SWEETSPOT", "TECHNIQUE", "STRENGTH",
    "ANAEROBIC", "VO2MAX", "LONG_ENDURANCE", "STRENGTH_ENDURANCE",
    "BRICK", "SKILL", "MOBILITY", "RECOVERY",
]
STATES = [
    "KEEP", "PROGRESS", "CONSOLIDATE", "REDUCE", "MOVE",
    "AVOID_COMBINATION", "INSUFFICIENT_EVIDENCE",
]
